<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Implementing hooks.
 */

/**
 * Implements hook_form_alter().
 */
function page_json_form_alter(&$form, &$form_state, $form_id) {

  // Alter the core site settings form
  if ($form_id == 'system_site_information_settings') {

    $site_api_key = \Drupal::config('system.site')->get('api_key');
    $form['site_api_key'] = array(
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => $site_api_key,
      '#attributes' => array('placeholder' => 'No API Key yet')
    );

    // Add additional submit handeler to save our custom settings
    $form['#submit'][] = 'Drupal\page_json\Controller\PageJsonController::page_json_form_submit';
  }
}

